name: 自动构建二进制文件

on:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Multi Client
        run: |
          sudo apt update
          sudo apt install git wget -y
          sudo wget https://dl.google.com/go/go1.23.4.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf go1.23.4.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          sudo git clone https://github.com/akile-network/akile_monitor
          cd akile_monitor/client
          sudo go mod download
          sudo go mod tidy
          sudo go mod verify
          sudo go build -o akile_client-linux-amd64
          sudo GOOS=linux GOARCH=arm64 go mod download
          sudo GOOS=linux GOARCH=arm64 go mod tidy
          sudo GOOS=linux GOARCH=arm64 go mod verify
          sudo GOOS=linux GOARCH=arm64 go build -o akile_client-linux-arm64
          sudo GOOS=windows GOARCH=amd64 go mod download
          sudo GOOS=windows GOARCH=amd64 go mod tidy
          sudo GOOS=windows GOARCH=amd64 go mod verify
          sudo GOOS=windows GOARCH=amd64 go build -o akile_client-windows-amd64.exe
          sudo GOOS=windows GOARCH=arm64 go mod download
          sudo GOOS=windows GOARCH=arm64 go mod tidy
          sudo GOOS=windows GOARCH=arm64 go mod verify
          sudo GOOS=windows GOARCH=arm64 go build -o akile_client-windows-arm64.exe
          sudo GOOS=darwin GOARCH=amd64 go mod download
          sudo GOOS=darwin GOARCH=amd64 go mod tidy
          sudo GOOS=darwin GOARCH=amd64 go mod verify
          sudo GOOS=darwin GOARCH=amd64 go build -o akile_client-darwin-amd64
          sudo GOOS=darwin GOARCH=arm64 go mod download
          sudo GOOS=darwin GOARCH=arm64 go mod tidy
          sudo GOOS=darwin GOARCH=arm64 go mod verify
          sudo GOOS=darwin GOARCH=arm64 go build -o akile_client-darwin-arm64
          sudo GOOS=freebsd GOARCH=amd64 go mod download
          sudo GOOS=freebsd GOARCH=amd64 go mod tidy
          sudo GOOS=freebsd GOARCH=amd64 go mod verify
          sudo GOOS=freebsd GOARCH=amd64 go build -o akile_client-freebsd-amd64
          sudo GOOS=freebsd GOARCH=arm64 go mod download
          sudo GOOS=freebsd GOARCH=arm64 go mod tidy
          sudo GOOS=freebsd GOARCH=arm64 go mod verify
          sudo GOOS=freebsd GOARCH=arm64 go build -o akile_client-freebsd-arm64
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "# akile_monitor 客户端二进制文件"
          tag_name: v0.0.2
          make_latest: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            akile_monitor/client/akile_client-linux-amd64
            akile_monitor/client/akile_client-linux-arm64
            akile_monitor/client/akile_client-windows-amd64.exe
            akile_monitor/client/akile_client-windows-arm64.exe
            akile_monitor/client/akile_client-darwin-amd64
            akile_monitor/client/akile_client-darwin-arm64
            akile_monitor/client/akile_client-freebsd-amd64
            akile_monitor/client/akile_client-freebsd-arm64
